
services:
  nodejs:
    build: .
    image: nikita_system_info_centos6
    container_name: nikita_system_info_centos6
    platform: linux/amd64 # Required on Apple M1
    volumes:
      - ../../../../:/nikita
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/system/env/info_centos6/test.coffee
