// Generated by CoffeeScript 2.5.1
var error;

error = require('../utils/error');

module.exports = function() {
  return {
    module: '@nikitajs/engine/src/metadata/depth',
    hooks: {
      'nikita:session:normalize': function(action) {
        // Move property from action to metadata
        if (action.hasOwnProperty('depth')) {
          action.metadata.depth = action.depth;
          delete action.depth;
        }
        return action.metadata.depth = action.parent ? action.parent.metadata.depth + 1 : 0;
      },
      'nikita:session:action': function(action) {
        // action.metadata.depth ?= 0
        if (typeof action.metadata.depth !== 'number') {
          throw error('METADATA_DEPTH_INVALID_VALUE', ["configuration `depth` expect an integer value,", `got ${JSON.stringify(action.metadata.depth)}.`]);
        }
      }
    }
  };
};
