
services:
  nodejs:
    build: .
    container_name: nikita_system_info_archlinux
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/system/env/info_archlinux/test.coffee
    image: nikita_system_info_archlinux
    networks:
      - nikita
    platform: linux/amd64 # Required on Apple M1
    volumes:
      - ../../../../:/nikita

networks:
  nikita:
    name: nikita
    driver: bridge
