// Generated by CoffeeScript 1.10.0
var mecano;

mecano = require('..');

module.exports.exec = function(comand, options, ignore_code, callback) {
  var cmd, machine, opts;
  machine = options.machine != null ? options.machine : options.machine = '--';
  if (!Array.isArray(options.code_skipped)) {
    options.code_skipped = [options.code_skipped];
  }
  if (ignore_code) {
    options.code_skipped.push(1);
  }
  cmd = "export SHELL=/bin/bash\nexport PATH=/opt/local/bin/:/opt/local/sbin/:/usr/local/bin/:/usr/local/sbin/:$PATH\nbin_boot2docker=$(command -v boot2docker)\nbin_docker=$(command -v docker)\nbin_machine=$(command -v docker-machine)\nif [ $bin_machine ];\n  then\n    if [ \"" + machine + "\" = \"--\" ];then exit 5;fi\n    eval $(${bin_machine} env " + machine + ") && $bin_docker " + comand + "\nelif [  $bin_boot2docker ];\n  then\n    eval $(${bin_boot2docker} shellinit) && $bin_docker " + comand + "\nelse\n  $bin_docker " + comand + "\nfi";
  opts = this.get_options(cmd, options);
  return mecano.execute(opts, function(err, executed, stdout, stderr) {
    if (err) {
      if (err.code === 5) {
        return callback(Error('Missing machine name as options'));
      }
    }
    return callback(err, executed, stdout, stderr);
  });
};

module.exports.get_options = function(cmd, options) {
  var exec_opts, i, k, len, ref;
  exec_opts = {
    cmd: cmd
  };
  ref = ['ssh', 'log', 'stdout', 'stderr', 'cwd', 'code', 'code_skipped', 'machine', 'force', 'container', 'image', 'entrypoint', 'trap_on_error', 'port', 'cmd'];
  for (i = 0, len = ref.length; i < len; i++) {
    k = ref[i];
    if (options[k] != null) {
      exec_opts[k] = options[k];
    }
  }
  return exec_opts;
};
