// Generated by CoffeeScript 1.9.1
var exec;

module.exports = function(ssh, pidfile, callback) {
  var child;
  if (arguments.length === 4) {
    throw Error('Argument "options" removed');
  }
  child = exec(ssh, "if [ ! -f '" + pidfile + "' ]; then exit 2; fi\nif ! kill -s 0 `cat '" + pidfile + "'`;\n  rm '" + pidfile + "';\n  then exit 2;\nfi");
  child.on('error', callback);
  return child.on('exit', function(code) {
    return callback(null, code === 0);
  });
};

exec = require('ssh2-exec');
