
services:
  nodejs:
    build: .
    image: nikita_service_centos7
    container_name: nikita_service_centos7
    volumes:
      - ../../../../:/nikita
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/service/env/centos7/test.coffee
