// Generated by CoffeeScript 2.3.2
require('@nikita/core/lib/registry').register({
  ldap: {
    acl: '@nikita/ldap/lib/acl',
    add: '@nikita/ldap/lib/add',
    delete: '@nikita/ldap/lib/delete',
    index: '@nikita/ldap/lib/index',
    schema: '@nikita/ldap/lib/schema',
    user: '@nikita/ldap/lib/user'
  }
});
