
services:
  nodejs:
    build: .
    image: nikita_tools_cron
    container_name: nikita_tools_cron
    volumes:
      - ../../../../:/nikita
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/tools/env/cron/test.coffee
