
services:
  nodejs:
    build: .
    container_name: nikita_system_tmpfs
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/system/env/tmpfs/test.coffee
    image: nikita_system_tmpfs
    networks:
      - nikita
    volumes:
      - ../../../../:/nikita

networks:
  nikita:
    name: nikita
    driver: bridge
