// Generated by CoffeeScript 2.4.1
require('@nikitajs/core/lib/registry').register({
  db: {
    database: {
      '': '@nikitajs/db/lib/database',
      exists: '@nikitajs/db/lib/database/exists',
      remove: '@nikitajs/db/lib/database/remove',
      wait: '@nikitajs/db/lib/database/wait'
    },
    query: '@nikitajs/db/lib/query',
    schema: {
      '': '@nikitajs/db/lib/schema',
      remove: '@nikitajs/db/lib/schema/remove'
    },
    user: {
      '': '@nikitajs/db/lib/user',
      exists: '@nikitajs/db/lib/user/exists',
      remove: '@nikitajs/db/lib/user/remove'
    }
  }
});
