
version: '3'
services:
  nodejs:
    build: .
    container_name: nikita_service_archlinux
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/service/env/archlinux/test.coffee
    image: nikita_service_archlinux
    volumes:
      - ../../../../:/nikita
    platform: linux/amd64
