// Generated by CoffeeScript 1.9.1
var docker, util;

module.exports = function(options, callback) {
  if (options.container == null) {
    return callback(Error('Missing container parameter'));
  }
  return docker.get_provider(options, (function(_this) {
    return function(err, provider) {
      var cmd, exec_opts, i, k, len, ref;
      if (err) {
        return callback(err);
      }
      options.provider = provider;
      cmd = docker.prepare_cmd(provider, options.machine);
      if (util.isError(cmd)) {
        return callback(cmd);
      }
      cmd += 'docker kill ';
      if (options.signal != null) {
        cmd += "-s " + options.signal + " ";
      }
      cmd += options.container;
      exec_opts = {
        cmd: cmd
      };
      ref = ['ssh', 'log', 'stdout', 'stderr', 'cwd', 'code', 'code_skipped'];
      for (i = 0, len = ref.length; i < len; i++) {
        k = ref[i];
        if (options[k] != null) {
          exec_opts[k] = options[k];
        }
      }
      return _this.execute(exec_opts, function(err, executed, stdout, stderr) {
        return callback(err, executed, stdout, stderr);
      });
    };
  })(this));
};

docker = require('./commons');

util = require('util');
