// Generated by CoffeeScript 1.9.1
var docker, util;

module.exports = function(options, callback) {
  if (options.image == null) {
    return callback(Error('Missing image parameter'));
  }
  if (options.destination == null) {
    return callback(Error('Missing destination parameter'));
  }
  return docker.get_provider(options, (function(_this) {
    return function(err, provider) {
      var cmd, exec_opts, i, k, len, ref;
      if (err) {
        return callback(err);
      }
      options.provider = provider;
      cmd = docker.prepare_cmd(provider, options.machine);
      if (util.isError(cmd)) {
        return callback(cmd);
      }
      cmd += "docker load -i " + options.source + " " + options.image;
      exec_opts = {
        cmd: cmd
      };
      ref = ['ssh', 'log', 'cwd', 'code', 'code_skipped'];
      for (i = 0, len = ref.length; i < len; i++) {
        k = ref[i];
        if (options[k] != null) {
          exec_opts[k] = options[k];
        }
      }
      return _this.execute(exec_opts, function(err, executed, stdout, stderr) {
        return callback(err, executed, stdout, stderr);
      });
    };
  })(this));
};

docker = require('./commons');

util = require('util');
