// Generated by CoffeeScript 1.10.0
var docker, docker_status, util;

module.exports = function(options, callback) {
  var cmd;
  if (options.container == null) {
    return callback(Error('Missing container parameter'));
  }
  cmd = ' start ';
  if (options.attach) {
    cmd += '-a ';
  }
  cmd += options.container;
  return docker_status(options, function(err, is_running) {
    if (is_running) {
      options.log({
        message: "Container already started " + options.container + " (Skipping)",
        level: 'INFO',
        module: 'mecano/lib/docker/start'
      });
    }
    if (err || is_running) {
      return callback(err, false);
    }
    options.log({
      message: "Starting container " + options.container,
      level: 'INFO',
      module: 'mecano/lib/docker/start'
    });
    return docker.exec(cmd, options, false, function(err, executed, stdout, stderr) {
      return callback(err, executed, stdout, stderr);
    });
  });
};

docker_status = require('./status');

docker = require('../misc/docker');

util = require('util');
