
services:
  nodejs:
    build: .
    image: nikita_core_sudo
    container_name: nikita_core_sudo_nodejs
    volumes:
      - ../../../../:/home/nikita/work
    environment:
      NIKITA_TEST_MODULE: /home/nikita/work/packages/core/env/sudo/test.coffee
