
services:
  nodejs:
    build: .
    container_name: nikita_core_sudo_nodejs
    environment:
      NIKITA_TEST_MODULE: /home/nikita/work/packages/core/env/sudo/test.coffee
    image: nikita_core_sudo
    networks:
      - nikita
    volumes:
      - ../../../../:/home/nikita/work

networks:
  nikita:
    name: nikita
    driver: bridge
