// Generated by CoffeeScript 2.5.1
var EventEmitter, path, stackTrace;

({EventEmitter} = require('events'));

stackTrace = require('stack-trace');

path = require('path');

module.exports = function() {
  return {
    module: '@nikitajs/engine/src/plugins/log',
    require: '@nikitajs/engine/src/plugins/events',
    hooks: {
      'nikita:session:action': {
        after: '@nikitajs/engine/src/plugins/events',
        handler: function(action) {
          return action.log = function(log) {
            var frame, ref, ref1;
            if (typeof log === 'string') {
              log = {
                message: log
              };
            }
            if (log.level == null) {
              log.level = 'INFO';
            }
            if (log.time == null) {
              log.time = Date.now();
            }
            if (log.index == null) {
              log.index = action.metadata.index;
            }
            if (log.module == null) {
              log.module = action.metadata.module;
            }
            if (log.namespace == null) {
              log.namespace = action.metadata.namespace;
            }
            if (log.type == null) {
              log.type = 'text';
            }
            log.depth = action.metadata.depth;
            log.metadata = action.metadata;
            log.config = action.config;
            frame = stackTrace.get()[1];
            log.filename = frame.getFileName();
            log.file = path.basename(frame.getFileName());
            log.line = frame.getLineNumber();
            if (typeof action.metadata.log === 'function') {
              if ((ref = action.metadata) != null) {
                ref.log(log);
              }
            } else {
              if (((ref1 = action.metadata) != null ? ref1.log : void 0) === false) {
                return;
              }
            }
            return action.operations.events.emit(log.type, log, action);
          };
        }
      }
    }
  };
};
