
services:
  nodejs:
    build: .
    image: nikita_docker_nodejs
    container_name: nikita_docker_nodejs
    volumes:
      - ../../../../:/nikita
    depends_on:
      - dind
      # Not working for now, waiting is implemented inside entrypoint.sh
      # dind:
      #   condition: service_healthy
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/docker/env/docker/test.coffee
      # DOCKER_HOST: 'tcp://dind:2375'
  dind:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ''
    expose:
      - "2375"
    # healthcheck:
    #   test: "bash -c 'echo > /dev/tcp/localhost/2375'"
    #   interval: 1s
    #   timeout: 5s
    #   retries: 50
    # logging:
    #   driver: none
