// Generated by CoffeeScript 2.5.0
var registry;

registry = require('@nikitajs/core/lib/registry');

registry.register({
  tools: {
    backup: '@nikitajs/tools/lib/backup',
    compress: '@nikitajs/tools/lib/compress',
    cron: {
      add: '@nikitajs/tools/lib/cron/add',
      remove: '@nikitajs/tools/lib/cron/remove'
    },
    extract: '@nikitajs/tools/lib/extract',
    dconf: '@nikitajs/tools/lib/dconf',
    rubygems: {
      'fetch': '@nikitajs/tools/lib/rubygems/fetch',
      'install': '@nikitajs/tools/lib/rubygems/install',
      'remove': '@nikitajs/tools/lib/rubygems/remove'
    },
    iptables: '@nikitajs/tools/lib/iptables',
    git: '@nikitajs/tools/lib/git',
    repo: '@nikitajs/tools/lib/repo',
    ssh: {
      keygen: '@nikitajs/tools/lib/ssh/keygen'
    },
    sysctl: '@nikitajs/tools/lib/sysctl'
  }
});

registry.deprecate('cron_add', '@nikitajs/tools/lib/cron/add');

registry.deprecate('cron_remove', '@nikitajs/tools/lib/cron/remove');
