
services:
  nodejs:
    build: .
    image: nikita_tools_centos6
    container_name: nikita_tools_centos6
    platform: linux/amd64 # Required on Apple M1
    volumes:
      - ../../../../:/nikita
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/tools/env/centos6/test.coffee
