// Generated by CoffeeScript 1.11.1
module.exports = function(options) {
  options.log({
    message: "Entering service.restart",
    level: 'DEBUG',
    module: 'mecano/lib/service/restart'
  });
  if (typeof options.argument === 'string') {
    if (options.name == null) {
      options.name = options.argument;
    }
  }
  if (!options.name) {
    throw Error("Invalid Name: " + (JSON.stringify(options.name)));
  }
  options.log({
    message: "Restart service " + options.name,
    level: 'INFO',
    module: 'mecano/lib/service/restart'
  });
  return this.execute({
    cmd: "service " + options.name + " restart"
  }, function(err, restarted) {
    if (err) {
      throw err;
    }
    if (restarted) {
      return options.store["mecano.service." + options.name + ".status"] = 'started';
    }
  });
};
