// Generated by CoffeeScript 1.10.0
module.exports = function(options, callback) {
  if (!options.name) {
    return callback(new Error("Missing required option 'name'"));
  }
  return this.service_status({
    name: options.name,
    code_started: options.code_started,
    code_stopped: options.code_stopped,
    shy: true
  }).execute({
    cmd: "service " + options.name + " start",
    unless: function() {
      return options.store["mecano.service." + options.name + ".status"] === 'started';
    }
  }, function(err, started) {
    if (err) {
      throw err;
    }
    if (started) {
      return options.store["mecano.service." + options.name + ".status"] = 'started';
    }
  }).then(callback);
};
