
services:
  nodejs:
    build: .
    image: nikita_system_info_centos7
    container_name: nikita_system_info_centos7
    volumes:
      - ../../../../:/nikita
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/system/env/info_centos7/test.coffee
