// Generated by CoffeeScript 1.12.5
var db;

module.exports = function(options) {
  var k, ref, ref1, v;
  if (options.db == null) {
    options.db = {};
  }
  ref = options.db;
  for (k in ref) {
    v = ref[k];
    if (options[k] == null) {
      options[k] = v;
    }
  }
  if (options.schema == null) {
    options.schema = options.argument;
  }
  if (!options.engine) {
    throw Error('Missing option: "engine"');
  }
  if (!options.schema) {
    throw Error('Missing option: "schema"');
  }
  if (!options.admin_username) {
    throw Error('Missing option: "admin_username"');
  }
  if (!options.admin_password) {
    throw Error('Missing option: "admin_password"');
  }
  options.engine = options.engine.toLowerCase();
  if ((ref1 = options.engine) !== 'postgres') {
    throw Error("Unsupport engine: " + (JSON.stringify(options.engine)));
  }
  return this.system.execute({
    cmd: db.cmd(options, "DROP SCHEMA IF EXISTS " + options.schema + ";")
  });
};

db = require('../../misc/db');
