
# TODO: implement variable substitution once default value is implemented
# see https://github.com/docker/compose/issues/2441

version: '2'
services:
  nodejs:
    build: .
    image: nikita_tools_centos7
    container_name: nikita_tools_centos7
    platform: linux/amd64 # MongoDB repo used in tests only available on x64 arch
    volumes:
      - ../../../../:/nikita
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/tools/env/centos7/test.coffee
