
services:
  nodejs:
    build: .
    container_name: nikita_core_rocky9_nodejs
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/core/env/rocky9/test.coffee
    image: nikita_core_rocky9
    networks:
      - nikita
    volumes:
      - ../../../../:/nikita

networks:
  nikita:
    name: nikita
    driver: bridge
