
services:
  nodejs:
    build: .
    image: nikita_system_user
    container_name: nikita_system_user
    volumes:
      - ../../../../:/nikita
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/system/env/user/test.coffee
