// Generated by CoffeeScript 2.3.1
// # `nikita.db.database(options, callback)`

// Create a database for the destination database.

// ## Options

// * `admin_username`   
//   The login of the database administrator.   
// * `admin_password`   
//   The password of the database administrator.   
// * `database` (Array or String)   
//   The database name(s) to which the user should be added.   
// * `engine`   
//   The engine type, can be MySQL or PostgreSQL, required.   
// * `host`   
//   The hostname of the database.   
// * `port`   
//   Port to the associated database.   
// * `user` (Array or String)   
//   Contains  user(s) to add to the database, optional.   

// This user will be granted superuser permissions (see above) for the database specified

// ## Create Database example

// ```js
// require('nikita').database.db({
//   admin_username: 'test',
//   admin_password: 'test',
//   database: 'my_db',
// }, function(err, status){
//   console.log(err ? err.message : 'Database created or modified: ' + status);
// });
// ```

// ## Run the tests

// ```
// cd docker/centos6
// # then
// docker-compose run --rm nodejs test/db/database.coffee
// # or
// docker-compose run --rm nodejs
// npm test test/db/database.coffee
// ```

// ## Source Code
var db;

module.exports = function(options) {
  var cmd_database_create, cmd_database_exists, i, k, len, ref, ref1, ref2, results, user, v;
  // Import options from `options.db`
  if (options.db == null) {
    options.db = {};
  }
  ref = options.db;
  for (k in ref) {
    v = ref[k];
    if (options[k] == null) {
      options[k] = v;
    }
  }
  if (options.database == null) {
    options.database = options.argument;
  }
  if (!options.host) {
    // Validate options
    throw Error('Missing option: "host"');
  }
  if (!options.admin_username) {
    throw Error('Missing option: "admin_username"');
  }
  if (!options.admin_password) {
    throw Error('Missing option: "admin_password"');
  }
  if (!options.database) {
    throw Error('Missing option: "database"');
  }
  if (!options.engine) {
    throw Error('Missing option: "engine"');
  }
  if (options.user == null) {
    options.user = [];
  }
  if (typeof options.user === 'string') {
    options.user = [options.user];
  }
  // Deprecation
  if (options.engine === 'postgres') {
    console.log('Deprecated Value: options "postgres" is deprecated in favor of "postgresql"');
    options.engine = 'postgresql';
  }
  // Defines and check the engine type
  options.engine = options.engine.toLowerCase();
  if ((ref1 = options.engine) !== 'mariadb' && ref1 !== 'mysql' && ref1 !== 'postgresql') {
    throw Error(`Unsupport engine: ${JSON.stringify(options.engine)}`);
  }
  this.log({
    message: `Database engine set to ${options.engine}`,
    level: 'INFO',
    module: 'nikita/db/database'
  });
  // Create database unless exist
  this.log({
    message: `Check if database ${options.database} exists`,
    level: 'DEBUG',
    module: 'nikita/db/database'
  });
  switch (options.engine) {
    case 'mariadb':
    case 'mysql':
      cmd_database_create = db.cmd(options, {
        database: null
      }, `CREATE DATABASE ${options.database} DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;`);
      cmd_database_exists = db.cmd(options, {
        database: options.database
      }, `USE ${options.database};`);
      break;
    case 'postgresql':
      cmd_database_create = db.cmd(options, {
        database: null
      }, `CREATE DATABASE ${options.database};`);
      cmd_database_exists = db.cmd(options, {
        database: options.database
      }, "\\dt");
  }
  this.system.execute({
    cmd: cmd_database_create,
    unless_exec: cmd_database_exists
  }, function(err, {status}) {
    if (status) {
      return this.log({
        message: `Database created: ${JSON.stringify(options.database)}`,
        level: 'WARN',
        module: 'nikita/db/database'
      });
    }
  });
  ref2 = options.user;
  results = [];
  for (i = 0, len = ref2.length; i < len; i++) {
    user = ref2[i];
    results.push((() => {
      var cmd_grant_privileges, cmd_has_privileges;
      this.call(function() {
        return this.log({
          message: `Check if user ${user} has PRIVILEGES on ${options.database} `,
          level: 'DEBUG',
          module: 'nikita/db/database'
        });
      });
      this.db.user.exists({
        engine: options.engine,
        username: user,
        admin_username: options.admin_username,
        admin_password: options.admin_password,
        port: options.port,
        host: options.host
      }, function(err, {status}) {
        if (!err && !status) {
          throw Error(`DB user does not exists: ${user}`);
        }
      });
      switch (options.engine) {
        case 'mariadb':
        case 'mysql':
          // cmd_has_privileges = db.cmd options, admin_username: null, username: user.username, password: user.password, database: options.database, "SHOW TABLES FROM pg_database"
          cmd_has_privileges = db.cmd(options, {
            database: 'mysql'
          }, `SELECT user FROM db WHERE db='${options.database}';`) + ` | grep '${user}'`;
          cmd_grant_privileges = db.cmd(options, {
            database: null
          }, `GRANT ALL PRIVILEGES ON ${options.database}.* TO '${user
          // FLUSH PRIVILEGES;
}' WITH GRANT OPTION;`);
          break;
        case 'postgresql':
          cmd_has_privileges = db.cmd(options, {
            database: options.database
          }, "\\l") + ` | egrep '^${user}='`;
          cmd_grant_privileges = db.cmd(options, {
            database: null
          }, `GRANT ALL PRIVILEGES ON DATABASE ${options.database} TO ${user}`);
      }
      return this.system.execute({
        cmd: `if ${cmd_has_privileges}; then\n  echo '[INFO] User already with privileges'\n  exit 3\nfi\necho '[WARN] User privileges granted'\n${cmd_grant_privileges}`,
        code_skipped: 3
      }, function(err, {status}) {
        if (status) {
          return this.log({
            message: `Privileges granted: to ${JSON.stringify(user)} on ${JSON.stringify(options.database)}`,
            level: 'WARN',
            module: 'nikita/db/database'
          });
        }
      });
    })());
  }
  return results;
};

// ## Dependencies
db = require('../../misc/db');
