
services:
  nodejs:
    build: .
    container_name: nikita_system_info_ubuntu
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/system/env/info_ubuntu/test.coffee
      DEBUG: 1
      # DEBUG: 0
    image: nikita_system_info_ubuntu
    networks:
      - nikita
    volumes:
      - ../../../../:/nikita

networks:
  nikita:
    name: nikita
    driver: bridge
