
version: '2'
services:
  nodejs:
    build: .
    image: nikita_system_info_ubuntu
    container_name: nikita_system_info_ubuntu
    volumes:
      - ../../../../:/nikita
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/system/env/info_ubuntu/test.coffee
      DEBUG: 1
      # DEBUG: 0
