// Generated by CoffeeScript 2.3.2
// # `nikita.ipa.user.exists`

// Check if a user exists inside FreeIPA.

// ## Options

// * `referer` (string, ?required)   
//   The HTTP referer of the request, required unless provided inside the `Referer`
//   header.
// * `uid` (string, required)   
//   Name of the user to check for existence, same as the username.
// * `username` (string, required)   
//   Name of the user to add, alias of `uid`.
// * `url` (string, required)    
//   The IPA HTTP endpoint, for example "https://ipa.domain.com/ipa/session/json"

// ## Exemple

// ```js
// require('nikita')
// .ipa.user.exists({
//   uid: 'someone',
//   referer: 'https://my.domain.com',
//   url: 'https://ipa.domain.com/ipa/session/json',
//   principal: 'admin@DOMAIN.COM',
//   password: 'XXXXXX'
// }, function(err, {status, exists}){
//   console.info(err ? err.message : status ?
//     'User was updated' : 'User was already set')
// })
// ```
var diff, string;

module.exports = {
  shy: true,
  handler: function({options}, callback) {
    var base, base1;
    if (options.uid == null) {
      options.uid = options.username;
    }
    if (options.http_headers == null) {
      options.http_headers = {};
    }
    if ((base = options.http_headers)['Accept'] == null) {
      base['Accept'] = 'applicaton/json';
    }
    if ((base1 = options.http_headers)['Referer'] == null) {
      base1['Referer'] = options.referer;
    }
    if (!options.uid) {
      throw Error(`Required Option: uid is required, got ${options.uid}`);
    }
    if (!options.url) {
      throw Error(`Required Option: url is required, got ${options.url}`);
    }
    if (!options.principal) {
      throw Error(`Required Option: principal is required, got ${options.principal}`);
    }
    if (!options.password) {
      throw Error(`Required Option: password is required, got ${options.password}`);
    }
    if (!options.http_headers['Referer']) {
      throw Error(`Required Option: referer is required, got ${options.http_headers['Referer']}`);
    }
    return this.ipa.user.show(options, {
      uid: options.uid,
      relax: true
    }, function(err) {
      var exists;
      if (err && err.code !== 4001) {
        return callback(err);
      }
      exists = !err;
      return callback(null, {
        status: exists,
        exists: exists
      });
    });
  }
};

// ## Dependencies
string = require('@nikitajs/core/lib/misc/string');

diff = require('object-diff');
