
version: '3'
services:
  nodejs:
    build: .
    image: nikita_service_ubuntu
    container_name: nikita_service_ubuntu
    volumes:
      - ../../../../:/nikita
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/service/env/ubuntu/test.coffee
