
services:
  nodejs:
    build: ./nodejs
    image: nikita_krb5_nodejs
    container_name: nikita_krb5_nodejs
    volumes:
      - ../../../../:/nikita
    depends_on:
      - krb5
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/krb5/env/krb5/test.coffee
  krb5:
    build: ./server
    image: nikita_krb5_kdc
    container_name: nikita_krb5_kdc
    volumes:
      - /dev/urandom:/dev/random
    logging:
      driver: none
    environment:
      BOOTSTRAP: 1
