// Generated by CoffeeScript 2.6.1
var normalize, properties;

module.exports = normalize = function(action) {
  if (Array.isArray(action)) {
    return action.map(function(action) {
      return normalize(action);
    });
  }
  return action;
};

properties = ['context', 'handler', 'hooks', 'metadata', 'config', 'parent', 'plugins', 'registry', 'run', 'scheduler', 'state'];
