// Generated by CoffeeScript 2.6.1
var crypto;

crypto = require('crypto');

module.exports = {
  sanitize: function(versions, fill = 'x') {
    var _, i, is_array, j, k, len, ref, version;
    is_array = Array.isArray(versions);
    if (!is_array) {
      versions = [versions];
    }
    for (i = j = 0, len = versions.length; j < len; i = ++j) {
      version = versions[i];
      version = version.split('.');
      version = version.slice(0, 3);
      for (_ = k = 0, ref = 3 - version.length; (0 <= ref ? k < ref : k > ref); _ = 0 <= ref ? ++k : --k) {
        version.push(fill);
      }
      version = version.map(function(v) {
        if (!isNaN(parseInt(v, 10))) {
          // Ubuntu style, remove trailing '0'
          return `${parseInt(v, 10)}`;
        }
        if (/\d+-\d+/.test(v)) {
          // Arch style, strip /-\d$/
          v = v.split('-')[0];
        }
        return v;
      });
      versions[i] = version.join('.');
    }
    if (is_array) {
      return versions;
    } else {
      return versions[0];
    }
  },
  satisfies: require('semver').satisfies
};
