
services:
  nodejs:
    build: .
    image: nikita_core_ubuntu_1404
    container_name: nikita_core_ubuntu_1404_nodejs
    volumes:
      - ../../../../:/nikita
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/core/env/ubuntu-14.04/test.coffee
      DEBUG: 1
      # DEBUG: 0
