// Generated by CoffeeScript 2.3.2
require('@nikitajs/core/lib/registry').register({
  krb5: {
    addprinc: '@nikitajs/krb5/lib/addprinc',
    delprinc: '@nikitajs/krb5/lib/delprinc',
    ktadd: '@nikitajs/krb5/lib/ktadd',
    ticket: '@nikitajs/krb5/lib/ticket',
    ktutil: {
      add: '@nikitajs/krb5/lib/ktutil/add'
    }
  }
});
