
services:
  nodejs:
    build: .
    image: nikita_core_chown
    container_name: nikita_core_chown_nodejs
    volumes:
      - ../../../../:/nikita
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/core/env/chown/test.coffee
