// Generated by CoffeeScript 2.3.2
require('@nikitajs/core/lib/registry').register({
  lxd: {
    config: {
      device: {
        add: '@nikitajs/lxd/lib/config/device/add'
      }
    },
    init: '@nikitajs/lxd/lib/init',
    delete: '@nikitajs/lxd/lib/delete',
    start: '@nikitajs/lxd/lib/start',
    stop: '@nikitajs/lxd/lib/stop',
    exec: '@nikitajs/lxd/lib/exec',
    file: {
      push: '@nikitajs/lxd/lib/file/push',
      exists: '@nikitajs/lxd/lib/file/exists'
    },
    network: {
      '': '@nikitajs/lxd/lib/network',
      create: '@nikitajs/lxd/lib/network',
      attach: '@nikitajs/lxd/lib/network/attach',
      detach: '@nikitajs/lxd/lib/network/detach',
      delete: '@nikitajs/lxd/lib/network/delete'
    },
    running: '@nikitajs/lxd/lib/running'
  }
});
