// Generated by CoffeeScript 2.3.2
require('@nikitajs/core/lib/registry').register({
  lxd: {
    exec: '@nikitajs/lxd/lib/exec',
    delete: '@nikitajs/lxd/lib/delete',
    file: {
      exists: '@nikitajs/lxd/lib/file/exists',
      push: '@nikitajs/lxd/lib/file/push'
    },
    init: '@nikitajs/lxd/lib/init',
    network: '@nikitajs/lxd/lib/network'
  }
});
