// Generated by CoffeeScript 2.4.1
// # `nikita.lxd.stop`

// Start a running Linux Container.

// ## Options

// * `container` (required, string)
//   The name of the container

// ## Example

// ```
// require('nikita')
// .lxd.stop({
//   container: "myubuntu"
// }, function(err, {status}) {
//   console.log( err ? err.message : 'The container was stopped')
// });
// ```

// ## Source Code
module.exports = function({options}) {
  this.log({
    message: "Entering stop",
    level: 'DEBUG',
    module: '@nikitajs/lxd/lib/stop'
  });
  if (!options.container) {
    throw Error("Argument 'name' is required to stop a container");
  }
  return this.system.execute({
    cmd: `lxc list -c ns --format csv | grep '${options.container},STOPPED' && exit 42\nlxc stop ${options.container}`,
    code_skipped: 42
  });
};
