
services:
  nodejs:
    build: .
    image: nikita_core_ubuntu_2204
    container_name: nikita_core_ubuntu_2204_nodejs
    volumes:
      - ../../../../:/nikita
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/core/env/ubuntu-22.04/test.coffee
      DEBUG: 1
      # DEBUG: 0
