
services:
  nodejs:
    build: .
    container_name: nikita_core_ubuntu_2204_nodejs
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/core/env/ubuntu-22.04/test.coffee
      DEBUG: 1
      # DEBUG: 0
    image: nikita_core_ubuntu_2204
    networks:
      - nikita
    volumes:
      - ../../../../:/nikita

networks:
  nikita:
    name: nikita
    driver: bridge
