
services:
  nodejs:
    build: .
    container_name: nikita_db_mysql_nodejs
    # To avoid an error in the latest versions: ERROR 2059 (HY000): Authentication plugin 'caching_sha2_password' cannot be loaded
    command: --default-authentication-plugin=caching_sha2_password
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/db/env/mysql/test.coffee
    image: nikita_db_mysql_nodejs
    networks:
      - nikita
    volumes:
      - ../../../../:/nikita
  mysql:
    container_name: nikita_db_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootme
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql"]
      timeout: 20s
      retries: 10
    image: mysql:latest
    # logging:
    #   driver: none
    networks:
      - nikita

networks:
  nikita:
    name: nikita
    driver: bridge
