
# TODO: implement variable substitution once default value is implemented
# see https://github.com/docker/compose/issues/2441

version: '2'
services:
  nodejs:
    build: .
    image: nikita_db_mysql_nodejs
    container_name: nikita_db_mysql_nodejs
    volumes:
      - ../../../../:/nikita
    depends_on:
      - mysql
    environment:
      NIKITA_TEST_MODULE: /nikita/packages/db/env/mysql/test.coffee
  mysql:
    image: mysql:latest
    container_name: nikita_db_mysql_db
    # To avoid an error in the latest versions: ERROR 2059 (HY000): Authentication plugin 'caching_sha2_password' cannot be loaded
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootme
    expose:
      - "3306"
