// Generated by CoffeeScript 1.12.5
module.exports = {
  shy: true,
  handler: function(options) {
    options.log({
      message: "Entering connection.assert",
      level: 'DEBUG',
      module: 'nikita/lib/connection/assert'
    });
    return this.system.execute({
      cmd: "bash -c 'echo > /dev/tcp/" + options.host + "/" + options.port + "'"
    }, function(err) {
      if (err) {
        throw Error("Address not listening: \"" + options.host + ":" + options.port + "\"");
      }
    });
  }
};
